name: Task
description: Define a scoped piece of work
labels: []
body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: What needs to be done and why?
      validations:
          required: true

    - type: textarea
      id: acceptance
      attributes:
          label: Acceptance Criteria
          description: How do we know this is done?
          placeholder: |
              - [ ] Criterion 1
              - [ ] Criterion 2
      validations:
          required: true

    - type: textarea
      id: out-of-scope
      attributes:
          label: Out of Scope
          description: What does this task explicitly NOT include?
          placeholder: List things that might seem related but are not part of this task
